import { fixture, browser, expect, assert, capture, reflow, contrast, prose, title, errors } from './fixtures/editorial-fixture.mjs'

try {
 const d=await fixture();await expect(d.page.getByRole('button',{name:'Record live',exact:false})).toBeVisible();await expect(d.page.getByRole('button',{name:'Import recording',exact:false})).toBeVisible();await expect(d.page.getByRole('button',{name:'Notifications'})).toHaveCount(0)
 await expect(d.page.locator('.desk-work-items')).toContainText('Needs review');await expect(d.page.locator('.desk-preview-tools')).toContainText('Review draft');await reflow(d.page);await capture(d.page,'dashboard-desktop-long');console.log(`Sampled light prose token minimum contrast: ${await contrast(d.page)}:1`)
 assert.equal(await d.page.evaluate(async()=>{await document.fonts.ready;return document.fonts.check('16px "Source Sans 3"') && document.fonts.check('18px "Source Serif 4"')}),true)
 await d.page.setViewportSize({width:390,height:844});await expect(d.page.locator('.desk-work-items')).toContainText('Needs review');await d.page.getByRole('button',{name:'Selected document',exact:true}).click();await expect(d.page.locator('.desk-preview-tools')).toContainText('Review draft');await reflow(d.page);await capture(d.page,'dashboard-mobile-long')
 console.log('PASS equal intake prominence, notification removal, shared desktop/mobile draft stage, local fonts, long-title reflow')
 const r=await fixture('session/review-fixture/final_report');const download=r.page.locator('#btn-download-final-docx-card');const approve=r.page.locator('#btn-approve-report')
 await expect(download).toBeDisabled();await expect(approve).toBeDisabled();await expect(r.page.locator('.archival-body-text')).toContainText('14. Synthetic');await r.page.locator('.archival-doc-footer-centered').scrollIntoViewIfNeeded();await expect(r.page.locator('.archival-doc-footer-centered')).toBeInViewport()
 await r.page.getByRole('button',{name:'Source context',exact:true}).click();await expect(r.page.locator('.source-pre')).toContainText('14. Synthetic');await r.page.getByRole('button',{name:'Hide source'}).click();await capture(r.page,'review-desktop-long')
 await r.page.getByRole('checkbox',{name:'I have reviewed this saved revision against the source.'}).check();r.state.approveFailure=true;await approve.click();await expect(r.page.getByRole('alert')).toContainText('Saved revision changed');await expect(download).toBeDisabled();r.state.approveFailure=false;await expect(approve).toBeDisabled();await r.page.getByRole('button',{name:'Reload report'}).click();await r.page.getByRole('checkbox',{name:'I have reviewed this saved revision against the source.'}).check();await approve.click();await expect(download).toBeEnabled();assert.equal(r.state.approvals[0].revision_id,'revision-1')
 const exportEvent=r.page.waitForEvent('download');await download.click();await exportEvent;await expect(r.page.getByRole('status')).toContainText('Approved document downloaded')
 await r.page.getByRole('button',{name:'Edit new revision'}).click();await expect(download).toBeDisabled();await r.page.getByLabel('Report text', {exact:true}).fill(prose+'\n\nSynthetic correction.');r.state.reportUnavailable=true;await r.page.getByRole('button',{name:'Save new draft revision'}).click();await expect(r.page.getByRole('alert')).toContainText('could not be refreshed');await expect(download).toBeDisabled();await expect(approve).toBeDisabled();assert.equal(r.state.revision.approval_status,'draft');r.state.reportUnavailable=false;await r.page.getByRole('button',{name:'Reload report'}).click();await expect(r.page.getByRole('alert')).toHaveCount(0)
 await r.page.getByRole('button',{name:'Revisions (2)'}).click();await r.page.getByRole('button',{name:'Restore for review'}).last().click();await expect(download).toBeDisabled();await expect(approve).toBeDisabled()
 await r.page.setViewportSize({width:390,height:844});await reflow(r.page);await capture(r.page,'review-mobile-long')
 await r.page.setViewportSize({width:720,height:450});await reflow(r.page);await capture(r.page,'review-720-logical-reflow');await r.page.setViewportSize({width:568,height:320});await reflow(r.page);await capture(r.page,'review-short-window');await r.page.setViewportSize({width:1440,height:900});await r.page.locator('#btn-sidebar-theme-toggle').click();await capture(r.page,'review-dark-desktop');console.log(`Sampled dark prose token minimum contrast: ${await contrast(r.page)}:1`);await r.page.setViewportSize({width:390,height:844});await reflow(r.page);await capture(r.page,'review-dark-mobile')
 r.state.revision.approval_status='legacy_unreviewed';await r.page.reload();await expect(r.page.getByText('LEGACY REPORT • REVIEW REQUIRED',{exact:true})).toBeVisible();await expect(download).toBeDisabled();await expect(approve).toBeDisabled()
 console.log('PASS explicit revision approval, stale 409 gate, gated export, edit/restore invalidation and long-content review reflow')
 const h=await fixture('sessions');await expect(h.page.locator('.sessions-cards-grid')).toContainText('Needs review');h.state.archiveFailure=true;await h.page.getByRole('button',{name:'Archive session',exact:true}).click();await expect(h.page.getByRole('dialog')).toContainText('Original audio, transcripts and revisions remain preserved');await h.page.getByRole('dialog').getByRole('button',{name:'Archive session',exact:true}).click();await expect(h.page.getByRole('alert').filter({hasText:'remains in active work'})).toBeVisible();await expect(h.page.locator('.sessions-cards-grid')).toContainText(title)
 h.state.archiveFailure=false;await h.page.getByRole('button',{name:'Archive session',exact:true}).click();await h.page.getByRole('dialog').getByRole('button',{name:'Archive session',exact:true}).click();await expect(h.page.locator('.sessions-cards-grid')).toHaveCount(0);await h.page.getByRole('button',{name:'Archived sessions',exact:true}).click();await expect(h.page.locator('.sessions-cards-grid')).toContainText(title);await h.page.getByRole('button',{name:'Restore session',exact:true}).click();await h.page.getByRole('button',{name:'Active sessions',exact:true}).click();await expect(h.page.locator('.sessions-cards-grid')).toContainText(title);await capture(h.page,'history-desktop')
 console.log('PASS archive confirmation/source-retention copy, failure recovery, active filtering and restore')
 const f=await fixture('session/review-fixture/report_processing');f.state.processing='in_progress';await f.page.reload();await expect(f.page.getByText('Preparing the draft from the verified transcript…',{exact:true})).toBeVisible();f.state.processing='failed';await expect(f.page.getByRole('button',{name:'Retry',exact:true})).toBeVisible({timeout:10000});await expect(f.page.locator('.error-desc')).toContainText('rejected');f.state.startError='AI provider is unavailable. Source and previous work are retained.';await f.page.getByRole('button',{name:'Retry',exact:true}).click();await expect(f.page.locator('.error-desc')).toContainText('AI provider is unavailable');await expect(f.page.getByRole('button',{name:'Review draft'})).toHaveCount(0);f.state.startError=null;await f.page.getByRole('button',{name:'Retry',exact:true}).click();await expect(f.page.getByText('Preparing the draft from the verified transcript…',{exact:true})).toBeVisible();await expect.poll(()=>f.state.startBodies.length).toBeGreaterThan(0);assert.equal(f.state.startBodies.at(-1).force_new,true);await capture(f.page,'processing-retry');await f.page.getByRole('button',{name:'Cancel Process',exact:true}).click();await expect(f.page.getByRole('alert')).toContainText('Cancellation could not be confirmed');await expect(f.page.getByText('Cancellation confirmed.',{exact:false})).toHaveCount(0);await f.page.keyboard.press('Escape');await expect(f.page.getByRole('dialog')).toHaveCount(0);assert.equal(await f.page.locator('.app-main-column').evaluate(el=>el.inert),false);
 console.log('PASS rejected output/provider unavailable visible, no false success, retry force_new contract and source preserved in fixture')
 console.log('PASS provider-unavailable recovery contract');
 for(const screen of ['new_live','transcribe','session/review-fixture/verification','session/review-fixture/reporting','session/review-fixture/editing','session/review-fixture/proofreading','reports','settings']) {
  const v=await fixture(screen);await v.page.waitForTimeout(500);await reflow(v.page);if(screen.endsWith('/verification')){const seek=v.page.getByRole('slider',{name:'Source playback position'});await seek.focus();await v.page.keyboard.press('ArrowRight');await expect(seek).toHaveValue('1');assert.notEqual(await seek.evaluate(el=>getComputedStyle(el).outlineStyle),'none')}if(screen==='reports')await expect(v.page.getByRole('button',{name:'Word Doc'})).toBeDisabled();if(screen.endsWith('/editing')){await v.page.getByRole('button',{name:'Reporter A (Structure)',exact:true}).click();await expect(v.page.getByRole('button',{name:'Reporter A (Structure)',exact:true})).toHaveAttribute('aria-pressed','true');await v.page.getByRole('button',{name:'Verified Transcript (Authority)',exact:true}).click();await expect(v.page.locator('.source-pre')).toContainText('14. Synthetic')}await capture(v.page,screen.replaceAll('/','-')+'-desktop');await v.page.setViewportSize({width:1170,height:635});await reflow(v.page);await capture(v.page,screen.replaceAll('/','-')+'-owner-viewport');await v.page.setViewportSize({width:390,height:844});await reflow(v.page);await capture(v.page,screen.replaceAll('/','-')+'-mobile');await v.context.close()
 }
 console.log('PASS intake, verification, reporting, editing, proofreading, report collection and settings desktop/mobile fixtures')
 const m=await fixture('settings',{width:390,height:844},'reduce');await expect(m.page.getByText('Partial • missing domain data')).toBeVisible();await expect(m.page.getByText('Not configured',{exact:true})).toBeVisible();await m.page.getByRole('button',{name:'Open navigation'}).click();await expect(m.page.getByRole('dialog',{name:'Main navigation'})).toBeVisible();assert.equal(await m.page.locator('.desk-navigation-drawer').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await capture(m.page,'drawer-reduced-settled');for(let i=0;i<3;i++){await m.page.keyboard.press('Escape');await m.page.getByRole('button',{name:'Open navigation'}).click()}await m.page.emulateMedia({reducedMotion:'no-preference'});await m.page.emulateMedia({reducedMotion:'reduce'});assert.equal(await m.page.locator('.desk-navigation-drawer').evaluate(el=>getComputedStyle(el).transitionDuration),'0s');await m.page.keyboard.press('Escape');await expect(m.page.getByRole('button',{name:'Open navigation'})).toBeFocused();await m.page.setViewportSize({width:568,height:320});await reflow(m.page);await capture(m.page,'settings-short-reduced');await m.page.getByRole('button',{name:'Open navigation'}).click();await m.page.setViewportSize({width:1440,height:900});await expect(m.page.getByRole('dialog',{name:'Main navigation'})).toHaveCount(0);assert.equal(await m.page.locator('.app-main-column').evaluate(el=>el.inert),false);await m.page.locator('#btn-sidebar-theme-toggle').click();await capture(m.page,'settings-dark-desktop');await m.page.setViewportSize({width:390,height:844});await capture(m.page,'settings-dark-mobile');m.state.readiness='offline';await m.page.getByRole('button',{name:'Refresh readiness'}).click();await expect(m.page.getByText('Readiness unknown',{exact:false})).toBeVisible();m.state.readiness='partial';await m.page.getByRole('button',{name:'Retry readiness'}).click();await expect(m.page.getByText('Partial • missing domain data')).toBeVisible()
 console.log('PASS partial readiness, provider configuration distinction, reduced drawer snap/focus, short viewport and dark theme')
 // Pure rendered recording fixture: no AudioContext/MediaRecorder/device access.
 const live=await fixture();await live.page.evaluate(async ({prose,title})=>{
  const React=(await import('/node_modules/.vite/deps/react.js')).default;const {createRoot}=(await import('/node_modules/.vite/deps/react-dom_client.js')).default;const {AppShell}=await import('/src/components/common/AppShell.jsx');const {AuthProvider}=await import('/src/context/AuthContext.jsx');const {LiveRecordingView}=await import('/src/components/recording/LiveRecordingView.jsx');document.querySelector('#root').style.display='none';const host=document.createElement('div');document.body.append(host);createRoot(host).render(React.createElement(AuthProvider,null,React.createElement(AppShell,{activeView:'live_recording',screenTitle:'Live recording',onNavigate:()=>{}},React.createElement(LiveRecordingView,{sessionMetadata:{title,minister:'Synthetic speaker'},elapsedTime:7215,audioLevel:35,hasAudioSignal:true,liveTranscript:[{text:prose,start_time:5}],onStopRecording:()=>{window.__stop=true},onMinimize:()=>{},onToggleManualFlag:()=>{}}))))
 },{prose,title});await expect(live.page.getByRole('button',{name:'Stop and save'})).toBeVisible();await expect(live.page.locator('.live-bar-timer')).toHaveText('02:00:15');await live.page.locator('.transcript-stream-container').evaluate(el=>el.scrollTop=0);await capture(live.page,'recording-synthetic-desktop');await live.page.setViewportSize({width:390,height:844});await reflow(live.page);await live.page.locator('.transcript-stream-container').evaluate(el=>el.scrollTop=0);await capture(live.page,'recording-synthetic-mobile');await live.page.getByRole('button',{name:'Stop and save'}).click();assert.equal(await live.page.evaluate(()=>window.__stop),true)
 console.log('PASS isolated recording display long timer/prose, mobile urgent control and immediate stop callback (device lifecycle untested)')
 assert.deepEqual(errors,[])
 for(const c of browser.contexts())for(const p of c.pages())assert.equal(await p.evaluate(()=>window.__mic),0)
 console.log('PASS no uncaught page errors, microphone requests or real API/provider traffic')
} finally {await browser.close()}
